### PR TITLE
Farmer

### PR DESCRIPTION
**Pull request by QYuQianchen**
- Detect change in network and/or wallet change, and thus update states.
- Add `openFarmWithPermit` method in "Plant"
- Display spinner and disable button when actions are required from users (e.g. Sign a message, Sign and broadcast a tx)
- Use `claimAndClose` for "Harvest"
- Import Uniswap's "add liquidity" `<iframe>` to the FE. 
- Highlight the "Add liquidity" button only when the wallet is connected.

<update on 22nd Feb>
- Split harvest from destroy. 
- Link HOPR token to etherscan. 
- Add progress bar. 
- Auto update blocks every ten minutes
- Correct spinning and disable behavior when submitting a tx.
-  Include `closeFarm()` when nothing to harvest. 
- Auto refresh balances after tx gets mined.

<update on 23rd Feb>
- Update mainnet contract address.
- Remove testnet addresses
- Add link to uni pool token.

<update on 24th Feb>
- Remove check on `currentPeriod` for "Destroy". 
- Improve auto-refresh. 
- Change message of progress bar when period>13.

### CODE REVIEW

**Comment by QYuQianchen** [comment]
IPFS hash: [Qmdsa26Gu9WLKs5k4TjyZwMvV97RMJ5M3raLiGBji4Msxt](https://gateway.pinata.cloud/ipfs/Qmdsa26Gu9WLKs5k4TjyZwMvV97RMJ5M3raLiGBji4Msxt/)  @SCBuergel

**Comment by QYuQianchen** [comment]
[QmTLWqeRqN4NjDUFfgj1dURMDiaEhtV3UDoACy9Fjm2PVk](https://gateway.pinata.cloud/ipfs/QmTLWqeRqN4NjDUFfgj1dURMDiaEhtV3UDoACy9Fjm2PVk/)

**Comment by QYuQianchen** [comment]
[QmbaRm5Gs2Qno9m3vhHN8z65gNiotKDePmHKwV8nHMM2vm](https://gateway.pinata.cloud/ipfs/QmbaRm5Gs2Qno9m3vhHN8z65gNiotKDePmHKwV8nHMM2vm/)

**Comment by QYuQianchen** [comment]
[QmUtaPy6LKE82yuZvVbhU9wiXDaFYcYEgBaRYzXySfxbdH](https://gateway.pinata.cloud/ipfs/QmUtaPy6LKE82yuZvVbhU9wiXDaFYcYEgBaRYzXySfxbdH/)

**Review by 0xjjpa — APPROVED** [review]
LGTM!

**Pull request merged**
